[build]
  command = "npm install && npm run build"
  functions = "functions-build"
  publish = "build"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
    
# [[redirects]]
#  to = "/.netlify/functions/api/:splat"
#  from = "/api/*"
#  status = 200
#  force = true

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
